title: My Jekyll Site
email: b.priya0102@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A mern stack project on book  store.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
theme: jekyll-theme-primer

# Exclude files and directories from processing
exclude:
  - Backend/node_modules
  - Frontend/node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Build settings
markdown: kramdown