source "https://rubygems.org"

gem "jekyll", "~> 3.10.0"
gem "jekyll-seo-tag"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-coffeescript"
gem "faraday", "~> 2.0"
gem "faraday-retry"